version: '3.8'

services:
  python-ssh:
    build:
      args:
        - USER_GID=${USER_GID}
      dockerfile: ./Dockerfile
    container_name: python-ssh
    volumes:
      - ../src:/opt/src
      - ../configs:/configs
      - ./start.sh:/start.sh
    privileged: true
    networks:
      local_net:
        ipv4_address: 172.31.1.1
    ports:
      - "8000:8000"
      - "50000:22"
    tty: true
    command: "/bin/sh start.sh"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    volumes:
      - ../qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
    networks:
      local_net:
        ipv4_address: 172.31.1.2

  ollama:
      image: ollama/ollama
      ports:
        - "11434:11434"
      volumes:
        - ../ollama_data:/root/.ollama
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]
      environment:
        - OLLAMA_HOST=0.0.0.0:11434
      networks:
        local_net:
          ipv4_address: 172.31.1.3

networks:
  local_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
